# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='', help_text='ID de Unidad o Nombre de Alianza', max_length=255, unique=True, verbose_name='Identificador')),
                ('unit_type', models.CharField(choices=[('terapia_intensiva', 'Ambulancia de terapia intensiva'), ('urgencias_avanzadas', 'Ambulancia de urgencias avanzadas'), ('urgencias_basicas', 'Ambulancia de urgencias básicas'), ('vehiculo_consulta_medica_domicilio', 'Vehiculo consulta medica a domicilio')], max_length=255, verbose_name='Tipo de unidad')),
                ('is_active', models.BooleanField(default=True, help_text='Define si es una unidad activa', verbose_name='Esta activa')),
                ('is_assigned', models.BooleanField(default=False, help_text='Define si la unidad esta asignada o disponible', verbose_name='Esta asignada')),
                ('is_alliance', models.BooleanField(default=False, help_text='Define si es unidad de alianza', verbose_name='Es alianza')),
                ('location', models.CharField(blank=True, default='', help_text='Base para Locales y Zona para Alianzas', max_length=300, verbose_name='Base/Zona')),
                ('operator', models.CharField(blank=True, default='', help_text='Nombre del Operador de la unidad', max_length=50, verbose_name='Operador')),
                ('phone', models.CharField(blank=True, default='', help_text='Sólo necesario si es alianza', max_length=50, verbose_name='Teléfono')),
                ('description', models.TextField(blank=True, default='', help_text='Datos como modelo, placa, mantenimiento, etc.', verbose_name='Descripción de la unidad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alta')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
            ],
            options={
                'verbose_name_plural': 'Unidades',
            },
        ),
    ]
