# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-26 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('undefined', 'Indefinido'), ('terapia_intensiva', 'Ambulancia de terapia intensiva económico'), ('urgencias_avanzadas', 'Ambulancia de urgencias avanzadas económico'), ('urgencias_basicas', 'Ambulancia de urgencias básicas económico'), ('vehiculo_consulta_medica_domicilio', 'Vehículos de consulta médica a domicilio, Económico')], max_length=255, verbose_name='Tipo de unidad'),
        ),
    ]
