# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-12 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0002_auto_20180426_0438'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True, verbose_name='Nombre del medico')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alta')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
            ],
            options={
                'verbose_name_plural': 'Tripulacion',
            },
        ),
        migrations.CreateModel(
            name='CrewRoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True, verbose_name='Tipo de integrante')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alta')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
            ],
            options={
                'verbose_name_plural': 'Tipo de Tripulacion',
            },
        ),
        migrations.AddField(
            model_name='crewmembers',
            name='crewroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_roll_name', to='unit.CrewRoll', verbose_name='tipo de tripulacion'),
        ),
        migrations.AddField(
            model_name='unit',
            name='crew',
            field=models.ManyToManyField(blank=True, related_name='Tripulacion', to='unit.CrewMembers'),
        ),
    ]
