# Generated by Django 2.2.27 on 2022-05-17 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0003_auto_20180515_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewmember',
            name='crewroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='crew_members', to='unit.CrewRoll', verbose_name='Tipo de tripulación'),
        ),
    ]
