# Generated by Django 2.2.27 on 2022-06-23 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unit', '0004_auto_20220517_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewmember',
            name='user',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crewroll',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del Rol'),
        ),
    ]
