# Generated by Django 2.2.27 on 2022-06-23 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0005_auto_20220623_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewmember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
