# Generated by Django 2.2.27 on 2022-06-24 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0006_auto_20220623_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayUnitDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de turno')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='today_Doctor', to='unit.CrewMember', verbose_name='Doctor')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='today_Unit', to='unit.Unit', verbose_name='Unidad')),
            ],
        ),
    ]
