# Generated by Django 2.2.27 on 2022-06-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0008_todayunitdoctor_unit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todayunitdoctor',
            name='unit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio Roll Dia/Hora'),
        ),
    ]
