# Generated by Django 2.2.27 on 2022-06-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0009_auto_20220624_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='todayunitdoctor',
            name='unit_date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin Rol Dia/Hora'),
        ),
        migrations.AlterField(
            model_name='todayunitdoctor',
            name='unit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio Rol Dia/Hora'),
        ),
    ]
