# Generated by Django 2.2.27 on 2022-09-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0011_auto_20220909_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='crew',
            field=models.ManyToManyField(blank=True, related_name='units', to='unit.CrewMember', verbose_name='Miembros de Tripulación'),
        ),
    ]
