export const MODAL_RESET = 'MODAL_RESET';
export const MODAL_CHANGE_TAB = 'MODAL_CHANGE_TAB';

export const MODAL_UNITS_ADD = 'MODAL_UNITS_ADD';
export const MODAL_UNITS_REMOVE = 'MODAL_UNITS_REMOVE';
export const MODAL_UNITS_SET = 'MODAL_UNITS_SET';

export const REQUEST_SUGGEST_START = 'REQUEST_SUGGEST_START';
export const REQUEST_SUGGEST_SUCCESS = 'REQUEST_SUGGEST_SUCCESS';
export const REQUEST_SUGGEST_ERROR = 'REQUEST_SUGGEST_ERROR';

export const REQUEST_PATIENT_START = 'REQUEST_PATIENT_START';
export const REQUEST_PATIENT_SUCCESS = 'REQUEST_PATIENT_SUCCESS';
export const REQUEST_PATIENT_ERROR = 'REQUEST_PATIENT_ERROR';

export const REQUEST_UNITS_START = 'REQUEST_UNITS_START';
export const REQUEST_UNITS_SUCCESS = 'REQUEST_UNITS_SUCCESS';
export const REQUEST_UNITS_ERROR = 'REQUEST_UNITS_ERROR';

export const REQUEST_EMERGENCY_START = 'REQUEST_EMERGENCY_START';
export const REQUEST_EMERGENCY_SUCCESS = 'REQUEST_EMERGENCY_SUCCESS';
export const REQUEST_EMERGENCY_ERROR = 'REQUEST_EMERGENCY_ERROR';

export const REQUEST_EMERGENCY_TEXT_START = 'REQUEST_EMERGENCY_TEXT_START';
export const REQUEST_EMERGENCY_TEXT_SUCCESS = 'REQUEST_EMERGENCY_TEXT_SUCCESS';
export const REQUEST_EMERGENCY_TEXT_ERROR = 'REQUEST_EMERGENCY_TEXT_ERROR';
export const EMERGENCY_TEXT_CLEAR = 'EMERGENCY_TEXT_CLEAR';

export const REQUEST_NEW_INCIDENT_START = 'REQUEST_NEW_INCIDENT_START';
export const REQUEST_NEW_INCIDENT_SUCCESS = 'REQUEST_NEW_INCIDENT_SUCCESS';
export const REQUEST_NEW_INCIDENT_ERROR = 'REQUEST_NEW_INCIDENT_ERROR';

export const EMERGENCIES_ADD = 'EMERGENCIES_ADD';
export const EMERGENCIES_UPDATE = 'EMERGENCIES_UPDATE';

export const EMERGENCY_SET_INACTIVE_START = 'EMERGENCY_SET_INACTIVE_START';
export const EMERGENCY_SET_INACTIVE_SUCCESS = 'EMERGENCY_SET_INACTIVE_SUCCESS';
export const EMERGENCY_SET_INACTIVE_ERROR = 'EMERGENCY_SET_INACTIVE_ERROR';

export const EMERGENCY_SET_FINAL_GRADE_START =
  'EMERGENCY_SET_FINAL_GRADE_START';
export const EMERGENCY_SET_FINAL_GRADE_SUCCESS =
  'EMERGENCY_SET_FINAL_GRADE_SUCCESS';
export const EMERGENCY_SET_FINAL_GRADE_ERROR =
  'EMERGENCY_SET_FINAL_GRADE_ERROR';

export const EMERGENCY_SET_TIMER_UPDATE_START =
  'EMERGENCY_SET_TIMER_UPDATE_START';
export const EMERGENCY_SET_TIMER_UPDATE_SUCCESS =
  'EMERGENCY_SET_TIMER_UPDATE_SUCCESS';
export const EMERGENCY_SET_TIMER_UPDATE_ERROR =
  'EMERGENCY_SET_TIMER_UPDATE_ERROR';

export const EMERGENCY_SET_DERIVATION_UPDATE_START =
  'EMERGENCY_SET_DERIVATION_UPDATE_START';
export const EMERGENCY_SET_DERIVATION_UPDATE_SUCCESS =
  'EMERGENCY_SET_DERIVATION_UPDATE_SUCCESS';
export const EMERGENCY_SET_DERIVATION_UPDATE_ERROR =
  'EMERGENCY_SET_DERIVATION_UPDATE_ERROR';

export const EMERGENCY_TOGGLE_ACTIVE = 'EMERGENCY_TOGGLE_ACTIVE';

export const UNIT_DETAILS_START = 'UNIT_DETAILS_START';
export const UNIT_DETAILS_SUCCESS = 'UNIT_DETAILS_SUCCESS';
export const UNIT_DETAILS_ERROR = 'UNIT_DETAILS_ERROR';

export const SELECT_ADDRESS = 'SELECT_ADDRESS';

export const UPDATE_COPAGO_AMOUNT = 'UPDATE_COPAGO_AMOUNT';
