export const REQUEST_SUGGEST_START = 'REQUEST_SUGGEST_START';
export const REQUEST_SUGGEST_SUCCESS = 'REQUEST_SUGGEST_SUCCESS';
export const REQUEST_SUGGEST_ERROR = 'REQUEST_SUGGEST_ERROR';

export const REQUEST_PATIENT_START = 'REQUEST_PATIENT_START';
export const REQUEST_PATIENT_SUCCESS = 'REQUEST_PATIENT_SUCCESS';
export const REQUEST_PATIENT_ERROR = 'REQUEST_PATIENT_ERROR';
