# Generated by Django 2.2.27 on 2022-05-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unit', '0004_auto_20220517_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(max_length=10, verbose_name='Codigo de Servicio')),
                ('odoo_client', models.CharField(max_length=50, verbose_name='Cliente id(Legacy)')),
                ('erste_code', models.CharField(blank=True, default='', max_length=50, verbose_name='ID Code')),
                ('patient_name', models.CharField(default='', max_length=255, verbose_name='Nombre del Paciente')),
                ('patient_gender', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='', max_length=9, verbose_name='genero')),
                ('patient_age', models.IntegerField(blank=True, default=0, verbose_name='edad (años)')),
                ('patient_affiliations', models.CharField(blank=True, max_length=50, verbose_name='Filiacion')),
                ('patient_unknow', models.CharField(blank=True, max_length=50, verbose_name='Paciente Desconocido')),
                ('patient_clothes', models.CharField(blank=True, max_length=50, verbose_name='Vestimenta')),
                ('attention_place', models.CharField(blank=True, choices=[('Hogar', 'Hogar'), ('Escuela/Trabajo', 'Escuela/Trabajo'), ('Ins.deportivas', 'Ins.deportivas'), ('Ins. de recreacion', 'Ins. de recreacion'), ('Via Publica', 'Via Publica'), ('Otro', 'Otro')], default='', max_length=9, verbose_name='Sitio de Atencion')),
                ('skin_color', models.CharField(blank=True, default='', max_length=50, verbose_name='Coloración de piel')),
                ('service_type', models.CharField(blank=True, choices=[('Traslado', 'Traslado'), ('Urgencias', 'Urgencias'), ('Cuidados Intensivos', 'Cuidados Intensivos'), ('Consulta Medica', 'Consulta Medica')], default='', max_length=9, verbose_name='Tipo de Servicio')),
                ('consultation_reason', models.CharField(blank=True, choices=[('Cefalea', 'Cefalea'), ('Síncope', 'Síncope'), ('Inconciencia', 'Inconciencia'), ('Dolor Torácico', 'Dolor Torácico'), ('Otalgia', 'Otalgia'), ('Disfagia / odinofagia', 'Disfagia / odinofagia'), ('Disnea', 'Disnea'), ('Dolor Abdominal', 'Dolor Abdominal'), ('Fiebre', 'Fiebre'), ('Otros', 'Otros')], default='', max_length=20, verbose_name='Motivo de la Consulta')),
                ('event_type', models.CharField(blank=True, choices=[('No Traumaticos', 'No Traumaticos'), ('Traumaticos', 'Traumaticos')], default='', max_length=20, verbose_name='Motivo de la Consulta')),
                ('traumatics', models.CharField(blank=True, choices=[('Craneal', 'Craneal'), ('Craneoencefalico', 'Craneoencefalico'), ('Facial', 'Facial'), ('Cuello', 'Cuello'), ('Tórax', 'Tórax'), ('Abdomen', 'Abdomen'), ('Extremidades', 'Extremidades'), ('Columna vertebral', 'Columna vertebral'), ('Genitales', 'Genitales'), ('Otros', 'Otros')], default='', max_length=20, verbose_name='Motivo de la Consulta')),
                ('airway', models.CharField(blank=True, choices=[('Ninguno', 'Ninguno'), ('Manual', 'Manual'), ('Orofaringea', 'Orofaringea'), ('Endotraqueal', 'Endotraqueal'), ('Nasofaringea', 'Nasofaringea'), ('Ventilador', 'Ventilador'), ('Aspiracion', 'Aspiracion'), ('P.N l/min', 'P.N l/min'), ('M', 'M')], default='', max_length=20, verbose_name='Motivo de la Consulta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alta')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('units', models.ManyToManyField(blank=True, related_name='units_assign', to='unit.Unit')),
            ],
            options={
                'verbose_name_plural': 'Parte Medico',
                'ordering': ['created_at'],
            },
        ),
    ]
