# Generated by Django 2.2.27 on 2022-05-19 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalreport',
            name='erste_code',
        ),
        migrations.RemoveField(
            model_name='medicalreport',
            name='odoo_client',
        ),
        migrations.RemoveField(
            model_name='medicalreport',
            name='units',
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='normal_abdomen',
            field=models.BooleanField(blank=True, default=False, verbose_name='Abdomen'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='normal_face',
            field=models.BooleanField(blank=True, default=False, verbose_name='Face'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='normal_genitals',
            field=models.BooleanField(blank=True, default=False, verbose_name='Genitales'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='normal_head',
            field=models.BooleanField(blank=True, default=False, verbose_name='Cabeza'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='normal_limbs',
            field=models.BooleanField(blank=True, default=False, verbose_name='Extremidades'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='normal_spine',
            field=models.BooleanField(blank=True, default=False, verbose_name='Columna Vertebral'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='normal_torax',
            field=models.BooleanField(blank=True, default=False, verbose_name='Tórax'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='pe_blood_pressure',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Presion Arterial'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='pe_glassgow',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Glassgow'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='pe_glucometry',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Glucometria'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='pe_heart_rate',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Frequencia Cardiaca'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='pe_oxygen_saturation',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Saturacion O2'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='pe_respiratory_rate',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Frequencia Respiratoria'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='pe_temperature',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Temperature'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='pe_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Dia/Hora'),
            preserve_default=False,
        ),
    ]
