# Generated by Django 2.2.27 on 2022-06-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0003_auto_20220526_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='service_unit',
            field=models.CharField(default='', max_length=10, verbose_name='Unidad Movil'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='service_unit_plate',
            field=models.CharField(default='', max_length=10, verbose_name='No.Placas'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='service_unit_type',
            field=models.CharField(default='', max_length=10, verbose_name='Tipo Unidad'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='service_code',
            field=models.CharField(default='', max_length=10, verbose_name='Codigo de Servicio'),
        ),
    ]
