# Generated by Django 2.2.27 on 2022-06-03 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paperless', '0004_auto_20220603_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
            preserve_default=False,
        ),
    ]
