# Generated by Django 2.2.27 on 2022-06-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0006_auto_20220603_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='service_unit_type',
            field=models.CharField(default='', max_length=50, verbose_name='Tipo Unidad'),
        ),
    ]
