# Generated by Django 2.2.27 on 2022-06-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0007_auto_20220604_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='pe_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Dia/Hora'),
        ),
    ]
