# Generated by Django 2.2.27 on 2022-06-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0008_auto_20220604_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='pe_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dia/Hora'),
        ),
    ]
