# Generated by Django 2.2.27 on 2022-06-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0010_auto_20220606_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='current_condition',
            field=models.TextField(blank=True, verbose_name='Padecimiento Actual'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='current_therapeutics',
            field=models.TextField(blank=True, verbose_name='Tiempo de Evolucion y Terapeutica Actual'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='derivation',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default=False, max_length=20, verbose_name='Derivacion'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='derivation_place',
            field=models.TextField(blank=True, verbose_name='Notas Derivacion'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='description_of_injuries',
            field=models.TextField(blank=True, verbose_name='Descripcion de lesiones'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='diagnostic_impresion',
            field=models.TextField(blank=True, verbose_name='Impresion Diagnostica'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='pathological_history_alergy',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default=False, max_length=10, verbose_name='Alergias'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='pathological_history_arterial_hypertension',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default=False, max_length=10, verbose_name='Hipertension Arterial'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='pathological_history_daibetes_melitus',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default=False, max_length=10, verbose_name='Diabetes Melitus'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='pathological_history_heart_disease',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default=False, max_length=10, verbose_name='Cardiopatias'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='pathological_history_pneumopathies',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default=False, max_length=10, verbose_name='Neumopatias'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='pathological_history_trauma',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default=False, max_length=10, verbose_name='Quirurgicos/Trauma'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='patient_phone',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Telefono:'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='pupil_state',
            field=models.CharField(blank=True, choices=[('Isocoria', 'Isocoria'), ('Midriasis', 'Midriasis'), ('Miosis', 'Miosis'), ('Anisocoria', 'Anisocoria')], default='', max_length=20, verbose_name='Estado de las Pupilas'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='state_of_health',
            field=models.CharField(blank=True, choices=[('Delicado', 'Delicado'), ('Grave', 'Grave'), ('Muy Grave', 'Muy Grave')], default=False, max_length=20, verbose_name='Derivacion'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='treatment',
            field=models.TextField(blank=True, verbose_name='Tratamiento'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='normal_abdomen',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='', max_length=10, verbose_name='Abdomen'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='normal_face',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='', max_length=10, verbose_name='Face'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='normal_genitals',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='', max_length=10, verbose_name='Genitales'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='normal_head',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='', max_length=10, verbose_name='Cabeza'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='normal_limbs',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='', max_length=10, verbose_name='Extremidades'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='normal_spine',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='', max_length=10, verbose_name='Columna Vertebral'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='normal_torax',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='', max_length=10, verbose_name='Tórax'),
        ),
    ]
