# Generated by Django 2.2.27 on 2022-07-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0012_auto_20220713_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='other_pathological_history',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default=False, max_length=10, verbose_name='Otra enfermedad'),
        ),
    ]
