# Generated by Django 2.2.27 on 2022-07-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0016_auto_20220713_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='consultation_reason',
            field=models.CharField(blank=True, choices=[('Cefalea', 'Cefalea'), ('Síncope', 'Síncope'), ('Inconciencia', 'Inconciencia'), ('Dolor Torácico', 'Dolor Torácico'), ('Otalgia', 'Otalgia'), ('Disfagia / odinofagia', 'Disfagia / odinofagia'), ('Disnea', 'Disnea'), ('Dolor Abdominal', 'Dolor Abdominal'), ('Fiebre', 'Fiebre'), ('Otros', 'Otros')], default='', max_length=150, verbose_name='Motivo de la Consulta'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='copago_amount',
            field=models.CharField(blank=True, default='0', max_length=10, verbose_name='Co-pago'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='crum_reception',
            field=models.CharField(blank=True, default=False, max_length=120, verbose_name='Medico Recibe CRUM'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='other_consultation_reason',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Otro Motivo de la Consulta'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='other_pathological_history',
            field=models.CharField(blank=True, default=False, max_length=50, verbose_name='Otra enfermedad'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='state_of_health',
            field=models.CharField(blank=True, choices=[('Delicado', 'Delicado'), ('Grave', 'Grave'), ('Muy Grave', 'Muy Grave')], default=False, max_length=20, verbose_name='Estado de Salud'),
        ),
    ]
