# Generated by Django 2.2.27 on 2022-07-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0017_auto_20220713_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='traumatics',
            field=models.CharField(blank=True, choices=[('Craneal', 'Craneal'), ('Craneoencefalico', 'Craneoencefalico'), ('Facial', 'Facial'), ('Cuello', 'Cuello'), ('Tórax', 'Tórax'), ('Abdomen', 'Abdomen'), ('Extremidades', 'Extremidades'), ('Columna vertebral', 'Columna vertebral'), ('Genitales', 'Genitales'), ('Otros', 'Otros')], default='', max_length=150, verbose_name='Traumatico'),
        ),
    ]
