# Generated by Django 2.2.27 on 2022-07-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0018_auto_20220713_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='airway',
            field=models.TextField(blank=True, default='', verbose_name='Via Aerea'),
        ),
    ]
