# Generated by Django 2.2.27 on 2022-07-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0020_auto_20220713_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='demarcation_relation',
            field=models.CharField(blank=True, default=False, max_length=20, verbose_name='Deslinde'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='demarcation_responsable',
            field=models.CharField(blank=True, default=False, max_length=50, verbose_name='Deslinde'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='derivation_amount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Costo Derivacion'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='derivation_recive',
            field=models.CharField(blank=True, default=False, max_length=50, verbose_name='Medico que recibe'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='derivation_type',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('Hogar', 'Hogar'), ('Hospital', 'Hospital'), ('Otro', 'Otro')], default=False, max_length=20, verbose_name='Tipo Derivacion'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='electro_abnormalities',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Anormalidades'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='electro_axis_qrs',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Eje QRS'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='electro_frequency',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Frecuencia'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='electro_interpretation',
            field=models.TextField(blank=True, default='', verbose_name='Interpretacion'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='electro_pr',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='PR'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='electro_qt',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='QT'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='electro_rhythm',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Ritmo'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='electro_st',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='ST'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='electro_wave_p',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Onda P'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='electro_wave_t',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Onda T'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='medications',
            field=models.TextField(blank=True, default='', verbose_name='Exploracion Fisica'),
        ),
        migrations.RemoveField(
            model_name='medicalreport',
            name='physical_exploration',
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='physical_exploration',
            field=models.TextField(blank=True, default='', verbose_name='Exploracion Fisica'),
        ),
        migrations.DeleteModel(
            name='PhysicalExploration',
        ),
    ]
