# Generated by Django 2.2.27 on 2022-07-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0021_auto_20220714_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='copago_amount',
            field=models.CharField(blank=True, default=0, max_length=10, verbose_name='Co-pago'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='medications',
            field=models.TextField(blank=True, default='', verbose_name='Medicamentos'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='service_geo_lat',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='service_geo_lon',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Longitud'),
        ),
    ]
