# Generated by Django 2.2.27 on 2022-07-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0022_auto_20220714_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='copago_amount',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Co-pago'),
        ),
    ]
