# Generated by Django 2.2.27 on 2022-07-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0023_auto_20220714_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='derivation_amount',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Costo Derivacion'),
        ),
    ]
