# Generated by Django 2.2.27 on 2022-07-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0024_auto_20220714_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='patient_gender',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='', max_length=15, verbose_name='genero'),
        ),
    ]
