# Generated by Django 2.2.27 on 2022-08-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0026_auto_20220714_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='crum_hospital',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Hospitar recibe CRUM'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='crum_notes',
            field=models.TextField(blank=True, verbose_name='Notas Crum'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='derivation_hospital',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Hospitar derivacion'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='electro_qrs',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='QRS'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='email',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas Emergencia'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='send_email',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Se envio Email'),
        ),
    ]
