# Generated by Django 2.2.27 on 2022-08-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0028_auto_20220805_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='crew_medic',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Medico CREW'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='crew_medic_id_card',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Cedula Profesional'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='crew_operator',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Operador'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='crew_tum',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='TUM'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='det_normal_neck',
            field=models.TextField(blank=True, verbose_name='Notas Cuello'),
        ),
    ]
