# Generated by Django 2.2.27 on 2022-08-11 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0029_auto_20220811_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='final_report',
            field=models.FileField(blank=True, default='', upload_to='petfile/pdf_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg'])], verbose_name='archivo de estudios(pdf o jpg)'),
        ),
    ]
