# Generated by Django 2.2.27 on 2022-08-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0031_auto_20220818_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='signature_medic',
            field=models.TextField(blank=True, verbose_name='Signature Medic'),
        ),
    ]
