# Generated by Django 2.2.27 on 2022-08-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0032_medicalreport_signature_medic'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='odoo_client_data',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Socio'),
        ),
    ]
