# Generated by Django 2.2.27 on 2022-08-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0034_auto_20220823_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='demarcation_relation',
            field=models.CharField(blank=True, default=False, max_length=20, verbose_name='Deslinde relacion'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='demarcation_responsable',
            field=models.CharField(blank=True, default=False, max_length=50, verbose_name='Deslinde responsable'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='electro_abnormalities',
            field=models.TextField(blank=True, default='', max_length=100, verbose_name='Anormalidades'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='electro_axis_qrs',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Eje QRS'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='electro_frequency',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Frecuencia'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='electro_pr',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='PR'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='electro_qt',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='QT'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='electro_rhythm',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Ritmo'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='electro_st',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='ST'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='electro_wave_p',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Onda P'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='electro_wave_t',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Onda T'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='other_inmovilization_type',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Otra Inmovilizacion'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='other_pathological_history',
            field=models.CharField(blank=True, default=False, max_length=250, verbose_name='Otra enfermedad'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='other_traumatics',
            field=models.CharField(blank=True, choices=[('Craneal', 'Craneal'), ('Craneoencefalico', 'Craneoencefalico'), ('Facial', 'Facial'), ('Cuello', 'Cuello'), ('Tórax', 'Tórax'), ('Abdomen', 'Abdomen'), ('Extremidades', 'Extremidades'), ('Columna vertebral', 'Columna vertebral'), ('Genitales', 'Genitales'), ('Otros', 'Otros')], default='', max_length=150, verbose_name='Otro Traumatico'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='patient_address',
            field=models.CharField(default='', max_length=150, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='patient_affiliations',
            field=models.CharField(blank=True, max_length=150, verbose_name='Filiacion'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='skin_color',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Coloración de piel'),
        ),
    ]
