# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='modelo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de alta')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='ultima modificacion')),
            ],
            options={
                'verbose_name_plural': 'Marca',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('model', models.CharField(default='', max_length=50, verbose_name='modelo')),
                ('year', models.CharField(choices=[('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026')], default=0, max_length=4, verbose_name='año de fabricacion')),
                ('license_plate', models.CharField(max_length=10, unique=True, verbose_name='placa')),
                ('is_active', models.NullBooleanField(verbose_name='activa')),
                ('assigned', models.NullBooleanField(verbose_name='asignada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de alta')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='ultima modificacion')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_name', to='vehicle.Brand', verbose_name='marca')),
            ],
            options={
                'verbose_name_plural': 'Unidad',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de alta')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='ultima modificacion')),
            ],
            options={
                'verbose_name_plural': 'Tipo de Unidad',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_type_name', to='vehicle.UnitType', verbose_name='tipo de unidad'),
        ),
    ]
