MedicalReportDict = {
"odoo_client": "", 
"erste_code":  "", 
"service_code": "", 
"service_unit": "", 
"service_unit_type": "", 
"service_unit_plate": "", 
"service_geo_lat": "", 
"service_geo_lon": "", 
"patient_name": "", 
"patient_gender": "", 
"patient_age": "", 
"patient_affiliations": "",
"is_patient_unknow": "", 
"patient_unknow": "", 
"patient_clothes": "", 
"patient_phone": "",
"patient_address": "", 
"copago_amount": "",
"attention_place": "",
"other_attention_place": "", 
"skin_color": "", 
"service_type": "", 
"other_service_type": "",
"consultation_reason": [],
"other_consultation_reason": "", 
"event_type": "", 
"traumatics": [],
"other_traumatics": [], 
"airway": [],
"other_airway": "", 
"physical_exploration": [], 
"normal_elements": [],
"current_condition": "", 
"pupil_state_left": [], 
"pupil_state_right": [], 
"pathological_history": [],
"other_pathological_history": '', 
"current_therapeutics": "", 
"description_of_injuries": "", 
"diagnostic_impresion": "",
"treatment": "", 
"derivation": "", 
"derivation_place": "", 
"state_of_health": "",
"geo_key": "",
"demarcation": "",
"demarcation_responsable": "",
"demarcation_relation": "",
"crum": "",
"crum_reception": "",
"medications": [],
"inmovilization": "",
"inmovilization_type": [],
"other_inmovilization_type": "",
"electro_rhythm": "",
"electro_frequency": "",
"electro_wave_p": "",
"electro_pr": "",
"electro_axis_qrs": "",
"electro_st": "",
"electro_wave_t": "",
"electro_qt": "",
"electro_abnormalities": "",
"electro_interpretation": "",
"derivation_amount": "",
"derivation_recive": "",
"derivation_type": "",
"demarcation_responsable": "",
"demarcation_relation": "",
"electro_qrs":"",
"email": "",
"send_email":"",
"derivation_hospital": "",
"crum_hospital":"",
"crum_notes":"",
"notes":"",
"detail_pat_history_daibetes_melitus":"",
"detail_pat_history_arterial_hypertension":"",
"detail_pat_history_heart_disease":"",
"detail_pat_history_pneumopathies":"",
"detail_pat_history_trauma":"",
"detail_pat_history_alergy":"",
"det_normal_head":"",
"det_normal_face":"",
"det_normal_neck":"",
"det_normal_torax":"",
"det_normal_abdomen":"",
"det_normal_limbs":"",
"det_normal_genitals":"",
"det_normal_spine":"",
"crew_medic":"",
"crew_medic_id_card":"",
"crew_tum":"",
"crew_operator":"",
"signature_client":"",
"signature_medic":"",
}