# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-26 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomType',
            fields=[
                ('symptom_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='symptom id')),
                ('name', models.CharField(default='', max_length=20, verbose_name='symptom')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de alta')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='ultima modificacion')),
            ],
            options={
                'verbose_name_plural': 'Symptom Type',
                'ordering': ['name'],
            },
        ),
    ]
