# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttentionDerivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motive', models.CharField(blank=True, max_length=100, verbose_name='Motivo')),
                ('eventualities', models.TextField(blank=True, max_length=100, verbose_name='eventualidades')),
                ('reception', models.CharField(blank=True, max_length=100, verbose_name='quien recibe en hospital')),
                ('notes', models.TextField(blank=True, max_length=100, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de alta')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='ultima modificacion')),
            ],
            options={
                'verbose_name_plural': 'Derivacion',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttentionHospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='hospital')),
                ('address', models.TextField(blank=True, max_length=100, verbose_name='direccion')),
                ('phone', models.CharField(blank=True, default='', max_length=15, verbose_name='telefono')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de alta')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='ultima modificacion')),
            ],
            options={
                'verbose_name_plural': 'Hospital',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttentionKind',
            fields=[
                ('grade_type', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Grado')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Consulta')),
                ('description', models.TextField(default='', verbose_name='Descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de alta')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='ultima modificacion')),
            ],
            options={
                'verbose_name_plural': 'Tipo de Atención',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttentionZone',
            fields=[
                ('zone_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Zona id')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de alta')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='ultima modificacion')),
            ],
            options={
                'verbose_name_plural': 'Zona',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odoo_client', models.CharField(max_length=50, verbose_name='cliente id')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Inicio toma de datos')),
                ('end_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Fin toma de datos')),
                ('unit_assigned_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Asignacion de unidad')),
                ('unit_dispatched_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Despacho de unidad')),
                ('arrival_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Arrivo de unidad')),
                ('attention_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Inicio de atencion')),
                ('derivation_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Inicio de derivacion')),
                ('hospital_arrival', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Llegada hopital')),
                ('patient_arrival', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Paciente atencion hopital')),
                ('final_emergency_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Fin emergencia')),
                ('is_active', models.NullBooleanField(default=True, verbose_name='Activa')),
                ('address_street', models.CharField(blank=True, default='', max_length=100, verbose_name='Calle y numero')),
                ('address_extra', models.CharField(blank=True, default='', max_length=100, verbose_name='Calle')),
                ('address_zip_code', models.CharField(blank=True, default='', max_length=5, verbose_name='Codigo Postal')),
                ('address_county', models.CharField(blank=True, default='', max_length=50, verbose_name='Delegacion')),
                ('address_col', models.CharField(blank=True, default='', max_length=50, verbose_name='Colonia')),
                ('address_between', models.CharField(blank=True, default='', max_length=100, verbose_name='entre la calle')),
                ('address_and_street', models.CharField(blank=True, default='', max_length=100, verbose_name='y la calle')),
                ('address_ref', models.CharField(blank=True, default='', max_length=100, verbose_name='referencias')),
                ('address_front', models.CharField(blank=True, default='', max_length=100, verbose_name='fachada')),
                ('address_instructions', models.CharField(blank=True, default='', max_length=100, verbose_name='Instruccciones llegada')),
                ('address_notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('caller_name', models.CharField(blank=True, max_length=100, verbose_name='Persona que llama')),
                ('caller_relation', models.CharField(blank=True, max_length=50, verbose_name='Relacion con el paciente')),
                ('patient_name', models.CharField(default='', max_length=255, verbose_name='Nombre del Paciente')),
                ('patient_gender', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='', max_length=9, verbose_name='genero')),
                ('patient_age', models.IntegerField(blank=True, default=0, verbose_name='edad (años)')),
                ('patient_allergies', models.CharField(blank=True, default='', max_length=100, verbose_name='alergias')),
                ('patient_illnesses', models.CharField(blank=True, default='', max_length=100, verbose_name='Enfermedades diagnosticadas')),
                ('patient_notes', models.TextField(blank=True, default='', verbose_name='Notas paciente')),
                ('attention_justification', models.TextField(blank=True, default='', verbose_name='Justificación')),
                ('main_complaint', models.CharField(blank=True, default='', max_length=100, verbose_name='sintoma principal')),
                ('complaint_descriprion', models.TextField(blank=True, default='', verbose_name='descripcion de los sintomas')),
                ('subscription_type', models.CharField(blank=True, default='', max_length=100, verbose_name='subscripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de alta')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='ultima modificacion')),
                ('attention_final_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_attention_kind_name', to='emergency.AttentionKind', verbose_name='Grado de atencion final')),
                ('grade_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attention_kind_name', to='emergency.AttentionKind', verbose_name='Grado Emergencia')),
            ],
            options={
                'verbose_name_plural': 'Emergency',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Categoria')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alta')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='emergency',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_category_name', to='emergency.ServiceCategory', verbose_name='Tipo de emergencia'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_name', to='emergency.AttentionZone', verbose_name='zone'),
        ),
        migrations.AddField(
            model_name='attentionderivation',
            name='emergency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='derivation_emergency_name', to='emergency.Emergency', verbose_name='emergencia'),
        ),
        migrations.AddField(
            model_name='attentionderivation',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attention_hospital_name', to='emergency.AttentionHospital', verbose_name='hospital'),
        ),
    ]
