# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 17:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [

    ]

    operations = [
        migrations.CreateModel(
            name='AttentionKind',
            fields=[
                ('grade_type', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Grado')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Consulta')),
                ('description', models.TextField(default='', verbose_name='Descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de alta')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='ultima modificacion')),
            ],
            options={
                'verbose_name_plural': 'Kind of Attention',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttentionZone',
            fields=[
                ('zone_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Zona id')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de alta')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='ultima modificacion')),
            ],
            options={
                'verbose_name_plural': 'zone',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odoo_client', models.CharField(max_length=50, unique=True, verbose_name='cliente id')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='inicio')),
                ('end_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='fin')),
                ('is_active', models.NullBooleanField(verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de alta')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='ultima modificacion')),
                ('grade_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attention_kind_name', to='emergency.AttentionKind', verbose_name='tipo')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_name', to='emergency.AttentionZone', verbose_name='zone')),
            ],
            options={
                'verbose_name_plural': 'Emergency',
                'ordering': ['created_at'],
            },
        ),
    ]
