# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 18:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='test_duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), verbose_name='Duracion'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='test_timefield',
            field=models.TimeField(default='06:00', verbose_name='test timefield'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='fin'),
        ),
    ]
