# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_emergency_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergency',
            old_name='complaint_descriprion',
            new_name='complaint_description',
        ),
    ]
