# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_auto_20171124_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergency',
            name='test_duration',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='test_timefield',
        ),
    ]
