# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-16 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0003_auto_20180208_1211'),
    ]

    operations = [

        migrations.AddField(
            model_name='emergency',
            name='copago_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Monto de Copago'),
        ),

    ]
