# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0003_auto_20171124_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='odoo_client',
            field=models.CharField(max_length=50, verbose_name='cliente id'),
        ),
    ]
