# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-26 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0003_auto_20180208_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attentionderivation',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Servicios de Derivación'},
        ),
        migrations.AlterModelOptions(
            name='attentionhospital',
            options={'ordering': ['name'], 'verbose_name_plural': 'Hospitales'},
        ),
        migrations.AlterModelOptions(
            name='attentionkind',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Tipos de Atención'},
        ),
        migrations.AlterModelOptions(
            name='attentionzone',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Zonas'},
        ),
        migrations.AlterModelOptions(
            name='emergency',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Lista de incidentes'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categoría de Servicio '},
        ),
        migrations.AlterField(
            model_name='emergency',
            name='attention_final_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_attention_kind_name', to='emergency.AttentionKind', verbose_name='Grado de atención final'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='complaint_description',
            field=models.TextField(blank=True, default='', verbose_name='Descripción de los sintomas'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alta'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificación'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='main_complaint',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Sintoma principal'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='odoo_client',
            field=models.CharField(max_length=50, verbose_name='Cliente id'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='subscription_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Subscripción'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_name', to='emergency.AttentionZone', verbose_name='Zona de Atención'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Categoría'),
        ),
    ]
