# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 04:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0004_auto_20171129_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='address_and_street',
            field=models.CharField(blank=True, max_length=100, verbose_name='y la calle'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='address_between',
            field=models.CharField(blank=True, max_length=100, verbose_name='entre la calle'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='address_col',
            field=models.CharField(blank=True, max_length=50, verbose_name='Colonia'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='address_county',
            field=models.CharField(blank=True, max_length=50, verbose_name='Delegacion'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='address_extra',
            field=models.CharField(blank=True, max_length=100, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='address_front',
            field=models.CharField(blank=True, max_length=100, verbose_name='casa frente'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='address_instructions',
            field=models.CharField(blank=True, max_length=100, verbose_name='Instruccciones'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='address_notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='address_ref',
            field=models.CharField(blank=True, max_length=100, verbose_name='referencias'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='address_street',
            field=models.CharField(blank=True, max_length=100, verbose_name='Calle y numero'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='address_zip_code',
            field=models.CharField(blank=True, max_length=5, verbose_name='zip'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='arrival_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='fin'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='attention_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='fin'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='caller_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Persona que llama'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='caller_relation',
            field=models.CharField(blank=True, max_length=50, verbose_name='Relacion'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='complaint_descriprion',
            field=models.TextField(blank=True, default='', verbose_name='descripcion de los sintomas'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='derivation_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='fin'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='final_emergency_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='fin'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='hospital_arrival',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='fin'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='main_complaint',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='sintoma principal'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='patient_age',
            field=models.IntegerField(blank=True, default=0, verbose_name='edad'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='patient_allergies',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='alergias'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='patient_arrival',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='fin'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='patient_gender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femanino')], default=0, max_length=9, verbose_name='genero'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='patient_illnesses',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Enfermedades diagnosticadas'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='patient_notes',
            field=models.TextField(blank=True, default='', verbose_name='Notas paciente'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='required_attention',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Tipo de atencion requerida'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='subscription_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='subscripcion'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='unit_assigned_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='fin'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='unit_dispatched_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='fin'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='unit',
            field=models.ManyToManyField(related_name='unit_name', to='vehicle.Unit', verbose_name='Unidad'),
        ),
    ]
