# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 02:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0005_auto_20171205_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='address_and_street',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='y la calle'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='address_between',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='entre la calle'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='address_col',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='address_county',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Delegacion'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='address_extra',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='address_front',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='fachada'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='address_instructions',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Instruccciones llegada'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='address_notes',
            field=models.TextField(blank=True, default='', verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='address_ref',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='referencias'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='address_street',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Calle y numero'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='address_zip_code',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='zip'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='arrival_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='arrivo de unidad'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='attention_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='inicio de atencion'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='derivation_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='inicio de derivacion'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='fin toma de datos'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='final_emergency_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='fin emergencia'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='hospital_arrival',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='llegada hopital'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='patient_arrival',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='paciente atencion hopital'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='patient_gender',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femanino')], default='', max_length=9, verbose_name='genero'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='inicio toma de datos'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='unit',
            field=models.ManyToManyField(blank=True, related_name='unit_name', to='vehicle.Unit', verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='unit_assigned_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='asignacion de unidad'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='unit_dispatched_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='despacho de unidad'),
        ),
    ]
