# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0007_auto_20171206_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='address_zip_code',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='Codigo Postal'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='caller_relation',
            field=models.CharField(blank=True, max_length=50, verbose_name='Relacion con el paciente'),
        ),
    ]
