# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0008_auto_20171207_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='patient_age',
            field=models.IntegerField(blank=True, default=0, verbose_name='edad'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='patient_gender',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='', max_length=9, verbose_name='genero'),
        ),
    ]
