# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0008_auto_20171207_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergency',
            name='required_attention',
        ),
        migrations.AddField(
            model_name='emergency',
            name='attention_final_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_attention_kind_name', to='emergency.AttentionKind', verbose_name='Grado de atencion final'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='attention_justification',
            field=models.TextField(blank=True, default='', verbose_name='Justificaci\xf3n'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='patient_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name'),
        ),
    ]
