# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-12 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0008_emergency_tree_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='tel_local',
            field=models.CharField(blank=True, default='', max_length=33, verbose_name='Tel de contacto'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='tel_mobile',
            field=models.CharField(blank=True, default='', max_length=33, verbose_name='Movil de contacto'),
        ),
    ]
