# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0009_auto_20171214_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=100, unique=True, verbose_name='Categoria')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alta')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion')),
            ],
            options={
                'ordering': ['categorie'],
            },
        ),
    ]
