# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-12 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0009_auto_20190612_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='operation_notes',
            field=models.TextField(blank=True, default='', verbose_name='Notas Operativas'),
        ),
    ]
