# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-24 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0010_emergency_operation_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='partner_legalname',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Razon legal del socio'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='partner_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nombre del socio'),
        ),
    ]
