# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0010_auto_20171213_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
