# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0010_auto_20171214_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='service_categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_categorie_name', to='emergency.ServiceCategorie', verbose_name='Categoria'),
        ),
    ]
