# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0011_auto_20171213_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=200)),
                ('grado', models.IntegerField(blank=True, null=True)),
                ('children', models.ManyToManyField(blank=True, null=True, related_name='_symptom2_children_+', to='emergency.Symptom2')),
            ],
        ),
    ]
