# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-13 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0011_auto_20190724_0350'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyDerivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reception', models.CharField(blank=True, max_length=100, verbose_name='quien recibe en hospital')),
                ('notes', models.TextField(blank=True, max_length=100, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de alta')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='ultima modificacion')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='em_attention_hospital_name', to='emergency.AttentionHospital', verbose_name='hospital')),
            ],
            options={
                'ordering': ['created_at'],
                'verbose_name_plural': 'Derivacion de Emergencia',
            },
        ),
        migrations.AddField(
            model_name='emergency',
            name='derivation',
            field=models.ManyToManyField(blank=True, related_name='derivation_issue', to='emergency.EmergencyDerivation', verbose_name='Derivacion'),
        ),
    ]
