# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0012_merge_20171215_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='servicecategory',
            old_name='categorie',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='emergency',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_category_name', to='emergency.ServiceCategory', verbose_name='Tipo de emergencia'),
        ),
    ]
