# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-14 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0012_auto_20190813_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergency',
            name='derivation',
        ),
        migrations.AddField(
            model_name='emergency',
            name='derivations',
            field=models.ManyToManyField(blank=True, related_name='derivation_issue', to='emergency.EmergencyDerivation', verbose_name='Derivaciones'),
        ),
    ]
