# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0012_symptom2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='symptom2',
            options={'ordering': ['clave']},
        ),
        migrations.AlterField(
            model_name='symptom2',
            name='grado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
