# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-25 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0013_auto_20190814_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='sales_rep',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Vendedor'),
        ),
    ]
