# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 12:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0013_auto_20171215_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attentionkind',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Tipo de Atención'},
        ),
        migrations.AlterModelOptions(
            name='attentionzone',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Zona'},
        ),
        migrations.AlterField(
            model_name='emergency',
            name='arrival_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 7, 12, 39, 13, 443571, tzinfo=utc), verbose_name='Arrivo de unidad'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='attention_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 7, 12, 39, 13, 443585, tzinfo=utc), verbose_name='Inicio de atencion'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='derivation_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 7, 12, 39, 13, 443598, tzinfo=utc), verbose_name='Inicio de derivacion'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 7, 12, 39, 13, 443523, tzinfo=utc), verbose_name='Fin toma de datos'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='final_emergency_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 7, 12, 39, 13, 443637, tzinfo=utc), verbose_name='Fin emergencia'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='grade_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attention_kind_name', to='emergency.AttentionKind', verbose_name='Grado Emergencia'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='hospital_arrival',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 7, 12, 39, 13, 443611, tzinfo=utc), verbose_name='Llegada hopital'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='is_active',
            field=models.NullBooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='patient_age',
            field=models.IntegerField(blank=True, default=0, verbose_name='edad (años)'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='patient_arrival',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 7, 12, 39, 13, 443624, tzinfo=utc), verbose_name='Paciente atencion hopital'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='patient_name',
            field=models.CharField(default='', max_length=255, verbose_name='Nombre del Paciente'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 7, 12, 39, 13, 443493, tzinfo=utc), verbose_name='Inicio toma de datos'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='unit_assigned_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 7, 12, 39, 13, 443541, tzinfo=utc), verbose_name='Asignacion de unidad'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='unit_dispatched_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 7, 12, 39, 13, 443556, tzinfo=utc), verbose_name='Despacho de unidad'),
        ),
    ]
