# Generated by Django 2.2.27 on 2022-05-19 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0002_auto_20220519_2132'),
        ('emergency', '0015_auto_20220517_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='medical_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='medical_report', to='paperless.MedicalReport', verbose_name='Parte Medico'),
        ),
    ]
